# Generated by Django 3.1.6 on 2021-02-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='facebook_id',
            field=models.CharField(default='12', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram_id',
            field=models.CharField(default='12', max_length=255),
            preserve_default=False,
        ),
    ]
