# Generated by Django 3.1.6 on 2021-02-12 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20210212_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='Friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
